config/routes.rb
Rails.application.routes.draw do

  devise_for :admins do
    root :to => "admins#users"
  end
  resources :posts do
    resources :comments, shallow: true
  end

  resources :contests do
    member do
      post 'set_winner'
      get 'winner_window'
    end
    collection do
      get 'my', path: "my_contests"
    end
  end

  resources :brands do
    collection do
      get 'my', path: "my_brands"
      post :visit_brand_social
    end
  end
  post '/admins/agencies/:agency_id/disable' => 'admins#disable_agency', as: 'disable_agency'
  post '/admins/agencies/:agency_id/enable' => 'admins#enable_agency', as: 'enable_agency'
  post '/admins/users/:user_id/disable' => 'admins#disable_user', as: 'disable_user'
  post '/admins/users/:user_id/enable' => 'admins#enable_user', as: 'enable_user'
  delete '/admins/agencies/:agency_id/delete' => 'admins#delete_agency', as: 'delete_agency'
  delete '/admins/users/:user_id/delete' => 'admins#delete_user', as: 'delete_user'
  get '/admins/agencies' => 'admins#agencies', as: 'admin_agencies'
  get '/admins/users' => 'admins#users', as: 'admin_users'
  get '/admins' => 'admins#users', as: 'admin_root_path'

  resources :notifications

  devise_for :agencies, controllers: {registrations: "agency_registrations"}
  devise_for :users, :controllers => {passwords: "password" }
  post '/users/password' => 'password#create', :as => :user_forgot_password, :via => :post
  get 'agencies/change_password' => 'agencies#change_password'
  post 'agencies/update_password' => 'agencies#update_password'

  namespace :api, :defaults => {:format => :json} do

    resources :posts do
      member do
        get 'comments'
        post 'like'
        post 'unlike'
      end
      collection do
        get 'by_brand'
        get 'by_user'
        get 'by_contest'
        get 'my', path: "my_posts"
        get 'stream'
        get :show_without_authenticate
      end
    end
    resources :contests do
      collection do
        get 'by_brand'
        get 'by_following'
      end
      member do
        post 'claim_prize'
      end
    end

    resources :brands do
      member do
        post 'click'
        post 'follow'
        post 'unfollow'
        get 'check_follow'
      end
    end

    resources :comments

    get 'users/login' => 'users#login'
    resources :users do
      collection do
        get 'search'
        get :get_users
        post :update_facebook
        post :update_twitter
        post :update_instagram
      end
      member do
        post 'follow'
        post 'unfollow'
        get 'check_follow'
        post 'save_token'
        get 'followers'
        get 'following'
        get 'contests'
        get 'get_all_expose_of_user'
      end
    end
    post 'profile/update' => 'users#update_my_profile', as: 'update_profile'
    get 'profile' => 'users#profile'

    resources :notifications, only: :index do
      collection do
        post :read_notification
        get :count_unread_notifications
      end
    end

    resources :agencies

    get 'rankings/global' => 'rankings#global'
    get 'rankings/followers' => 'rankings#followers'
    get 'rankings/following' => 'rankings#following'

  end

  root 'brands#my'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

end

app/views/admins/agencies.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="page-header">
        <h1 class="text-center">Manage Agencies</h1>
      </div>
      <div class="pull-right"><%= will_paginate(@agencies, renderer: BootstrapPagination::Rails) %></div>
      <table class="table table-striped table-hover text-center">
        <thead>
          <tr>
            <th class="text-center">Company Name</th>
            <th class="text-center">Name</th>
            <th class="text-center">Email</th>
            <th class="text-center">Phone</th>
            <th colspan="2" class="text-center"></th>
          </tr>
        </thead>
        <tbody>
          <% @agencies.each do |agency| %>
          <tr>
            <td><%= agency.company_name %></td>
            <td class="text-center vertical-middle"><%= agency.full_name %></td>
            <td class="text-center vertical-middle"><%= agency.email %></td>
            <td class="text-center vertical-middle"><%= agency.phone %></td>
            <td class="text-center vertical-middle">
              <% if agency.enabled? %>
                <%= link_to "Disable", disable_agency_path(agency_id: agency.id, page: @agencies.current_page), class: "btn btn-default btn-xs btn-actions", method: :post %>
              <% else %>
                <%= link_to "Enable", enable_agency_path(agency_id: agency.id, page: @agencies.current_page), class: "btn btn-default btn-xs btn-actions", method: :post %>
              <% end %>
            </td>
            <td class="text-center vertical-middle">
              <%= link_to "Delete", delete_agency_path(agency_id: agency.id, page: @agencies.current_page), class: "btn btn-default btn-xs btn-actions", method: :delete, data: {confirm: "Are you sure?"} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="pull-right">
        <%= will_paginate(@agencies, renderer: BootstrapPagination::Rails) %>
      </div>
    </div>
  </div>
</div>

<br>
<br>

app/views/admins/users.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="page-header">
        <h1 class="text-center">Manage Users</h1>
      </div>
      <div class="pull-right">
        <%= will_paginate(@users, renderer: BootstrapPagination::Rails) %>
      </div>
      <table class="table table-striped table-hover text-center">
        <thead>
          <tr>
            <th class="text-center">Username</th>
            <th class="text-center">Name</th>
            <th class="text-center">Email</th>
            <th class="text-center">Phone</th>
            <th colspan="2" class="text-center"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
          <tr>
            <td><%= user.username %></td>
            <td class="text-center vertical-middle"><%= user.full_name %></td>
            <td class="text-center vertical-middle"><%= user.email %></td>
            <td class="text-center vertical-middle"><%= user.phone %></td>
            <td class="text-center vertical-middle">
              <% if user.enabled? %>
                <%= link_to "Disable", disable_user_path(user_id: user.id, page: @users.current_page), class: "btn btn-default btn-xs btn-actions", method: :post %>
              <% else %>
                <%= link_to "Enable", enable_user_path(user_id: user.id, page: @users.current_page), class: "btn btn-default btn-xs btn-actions", method: :post %>
              <% end %>
            </td>
            <td class="text-center vertical-middle">
              <%= link_to "Delete", delete_user_path(user_id: user.id, page: @users.current_page), class: "btn btn-default btn-xs btn-actions", method: :delete, data: {confirm: "Are you sure?"} %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
      <div class="pull-right">
        <%= will_paginate(@users, renderer: BootstrapPagination::Rails) %>
      </div>
    </div>
  </div>
</div>