config/routes.rb
Rails.application.routes.draw do

  devise_for :admins do
    root :to => "admins#users"
  end
  resources :posts do
    resources :comments, shallow: true
  end

  resources :contests do
    member do
      post 'set_winner'
      get 'winner_window'
    end
    collection do
      get 'my', path: "my_contests"
    end
  end

  resources :brands do
    collection do
      get 'my', path: "my_brands"
      post :visit_brand_social
    end
  end
  post '/admins/agencies/:agency_id/disable' => 'admins#disable_agency', as: 'disable_agency'
  post '/admins/agencies/:agency_id/enable' => 'admins#enable_agency', as: 'enable_agency'
  post '/admins/users/:user_id/disable' => 'admins#disable_user', as: 'disable_user'
  post '/admins/users/:user_id/enable' => 'admins#enable_user', as: 'enable_user'
  delete '/admins/agencies/:agency_id/delete' => 'admins#delete_agency', as: 'delete_agency'
  delete '/admins/users/:user_id/delete' => 'admins#delete_user', as: 'delete_user'
  get '/admins/agencies' => 'admins#agencies', as: 'admin_agencies'
  get '/admins/users' => 'admins#users', as: 'admin_users'
  get '/admins' => 'admins#users', as: 'admin_root_path'

  resources :notifications

  devise_for :agencies, controllers: {registrations: "agency_registrations"}
  devise_for :users, :controllers => {passwords: "password" }
  post '/users/password' => 'password#create', :as => :user_forgot_password, :via => :post
  get 'agencies/change_password' => 'agencies#change_password'
  post 'agencies/update_password' => 'agencies#update_password'

  namespace :api, :defaults => {:format => :json} do

    resources :posts do
      member do
        get 'comments'
        post 'like'
        post 'unlike'
      end
      collection do
        get 'by_brand'
        get 'by_user'
        get 'by_contest'
        get 'my', path: "my_posts"
        get 'stream'
        get :show_without_authenticate
      end
    end
    resources :contests do
      collection do
        get 'by_brand'
        get 'by_following'
      end
      member do
        post 'claim_prize'
      end
    end

    resources :brands do
      member do
        post 'click'
        post 'follow'
        post 'unfollow'
        get 'check_follow'
      end
    end

    resources :comments

    get 'users/login' => 'users#login'
    resources :users do
      collection do
        get 'search'
        get :get_users
        post :update_facebook
        post :update_twitter
        post :update_instagram
      end
      member do
        post 'follow'
        post 'unfollow'
        get 'check_follow'
        post 'save_token'
        get 'followers'
        get 'following'
        get 'contests'
        get 'get_all_expose_of_user'
      end
    end
    post 'profile/update' => 'users#update_my_profile', as: 'update_profile'
    get 'profile' => 'users#profile'

    resources :notifications, only: :index do
      collection do
        post :read_notification
        get :count_unread_notifications
      end
    end

    resources :agencies

    get 'rankings/global' => 'rankings#global'
    get 'rankings/followers' => 'rankings#followers'
    get 'rankings/following' => 'rankings#following'

  end

  root 'brands#my'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

end

app/models/contest.rb
class Contest < ActiveRecord::Base
  self.per_page = 18
  has_many :posts, dependent: :destroy
  validates :start_date, presence: true
  validates :end_date, presence: true
  validate :start_date_over_end_date
  # has_many :winners
  belongs_to :brand
  is_impressionable :counter_cache => true, :column_name => :cached_views, :unique => :request_hash

  has_attached_file :picture,
                    storage: :s3,
                    s3_credentials: File.join(Rails.root, 'config', 's3.yml'),
                    :styles => { preview: "600x600^", square: "600x600^", thumb: "100x100^" },
                    :default_url => lambda { |image| ActionController::Base.helpers.asset_path('ph.jpg') }
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/, presence: true

  after_create :notify_followers

  def submissions_count(scope=:all)
    self.submissions(scope).count
  end

  def winners
    User.where("id in (select user_id from winners where contest_id = ?)", self.id)
  end

  def brand_name
    self.brand.name
  end

  def picture_url
    self.picture.url
  end

  def picture_url_square
    self.picture.url(:square)
  end

  def picture_url_preview
    self.picture.url(:preview)
  end

  def picture_url_thumb
    self.picture.url(:thumb)
  end

  def current_date_server
    Time.now
  end

  def submissions(scope=:all)
    if scope == :all
      self.posts.order(cached_votes_total: :desc)
    elsif scope == :today
      self.posts.where("created_at > ?", Time.now.at_beginning_of_day).order(cached_votes_total: :desc)
    end
  end

  def status
    if self.end_date && self.end_date > Time.now && self.start_date < Time.now
      "OPEN"
    else
      "CLOSE"
    end
  end

  def start_date_over_end_date
    if start_date > end_date
      errors.add(:start_date, "can't be over the end date")
    end
  end

  private

  def notify_followers
    PushNotificationsWorker.perform_async(self.brand.id, self.id)
  end

end

app/controllers/api/contests_controller.rb
class API::ContestsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :authenticate_user_from_token!, except: [:index, :show, :by_brand]
  respond_to :json

  def index
    user = User.find(params[:user_id])
    following = user.all_following.map{ |f| f.id }
    current_time = Time.now.in_time_zone.utc
    if following.length == 0
      @contests = Contest.all.where('end_date > ? and start_date < ?', current_time, current_time)
                         .paginate(page: params[:page]).order(start_date: :desc)
    else
      @contests = Contest.all.where('(end_date > ? and start_date < ?) OR (end_date > ? and brand_id IN (?))', current_time, current_time, current_time, following)
                             .paginate(page: params[:page]).order(start_date: :desc)
    end

    respond_with @contests, only: [:id, :brand_id, :title, :description, :rules, :prizes, :start_date, :end_date, :location, :latitude, :longitude, :winner_id],
                            methods: [:brand_name, :picture_url, :picture_url_preview, :picture_url_square, :picture_url_thumb, :current_date_server],
                            location: "/"
  end

  def show
    @contest = Contest.find(params[:id])
    @brand = @contest.brand
    if current_user
      @submissions = @contest.submissions.paginate(page: params[:page]).order(created_at: :desc).map do |s|
        {id: s.id,
        contest_id: s.contest_id,
        uploader_id: s.uploader_id,
        text: s.text,
        cached_votes_up: s.cached_votes_up,
        image_url: s.image_url,
        image_url_square: s.image_url_square,
        image_url_preview: s.image_url_preview,
        image_url_thumb: s.image_url_thumb,
        brand: s.brand,
        current_user_likes: s.current_user_likes
        }
      end
    else
      @submissions = @contest.submissions.paginate(page: params[:page]).order(created_at: :desc).map do |s|
        { id: s.id,
          contest_id: s.contest_id,
          uploader_id: s.uploader_id,
          text: s.text,
          cached_votes_up: s.cached_votes_up,
          image_url: s.image_url,
          image_url_square: s.image_url_square,
          image_url_preview: s.image_url_preview,
          image_url_thumb: s.image_url_thumb,
          brand: s.brand
        }
      end
    end
    json = @contest.as_json()
    json[:current_date_server] = Time.now.in_time_zone
    date_end = json['end_date']
    #json.delete('end_date')
    json[:end_date_text] = date_end.strftime("%I:%M %p - %a %B %d, %Y") unless date_end.blank?
    hash = {contest: {status: @contest.status, info: json},
            brand: @brand, submissions: {count: @submissions.count, submissions: @submissions},
            winners: @contest.winners}
    impressionist(@contest, "contest")
    respond_with hash, location: '/'
  end

  def by_following
    @user = User.find(params[:user_id])
    @following = @user.all_following.map{ |f| f.id }
    @contests = Contest.where(brand_id: @following)
                       .where('end_date > ?', Time.now.in_time_zone).order(start_date: :desc)
    respond_with @contests, methods: [:brand_name, :picture_url, :picture_url_preview, :picture_url_square, :picture_url_thumb], location: "/"
  end

  def by_brand
    @contests = Contest.where('brand_id = ? AND end_date > ?',params[:brand_id], Time.now.in_time_zone)
                       .paginate(page: params[:page]).order(start_date: :desc)
    respond_with @contests, methods: [:brand_name, :picture_url, :picture_url_preview, :picture_url_square, :picture_url_thumb], location: "/"
  end

  def claim_prize
    @contest = Contest.find(params[:id])
    @user = current_user
    if @user.won?(@contest)
      w = params[:winner]
      winner = OpenStruct.new(
        first_name: w[:first_name],
        last_name: w[:last_name],
        email: w[:email],
        phone: w[:phone],
        street: w[:street],
        city: w[:city],
        province: w[:province],
        postal_code: w[:postal_code]
      )
      NotificationsMailer.contact_agency(@contest, @user, winner).deliver!

      notification = Notification.find(params[:notification_id])
      unless notification.nil?
        notification.claimed
        post = Post.find(notification.post_id)
        winner = User.find(notification.receiver_id)
        sender = Agency.find(notification.sender_id)
        NotificationsMailer.winner(notification,post,winner,sender).deliver!
      end

      json = {status: "sent", winner: winner}.to_json
      respond_with json, location: '/'
    else
      error = {error: "this user have not won the contest"}.to_json
      respond_with error, status: :unprocessable_entity, location: "/"
    end
  end

end

app/controllers/contests_controller.rb
class ContestsController < ApplicationController
  before_action :authenticate_admin!,only: [:index]
  before_action :set_contest, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_agency!, only: [:create, :update, :destroy, :edit, :new, :my, :set_winner]
  before_action :correct_agency, only: [:edit, :update, :destroy]
  impressionist :actions=>[:show, :index], :unique => [:impressionable_type, :impressionable_id, :session_hash]

  # GET /contests
  # GET /contests.json
  def index
    @contests = Contest.all.paginate(page: params[:page]).order(start_date: :desc)
  end

  def my
    @contests = current_agency.contests.paginate(page: params[:page]).order(start_date: :desc)
    render 'my_contests'
  end

  # GET /contests/1
  # GET /contests/1.json
  def show
    @posts = @contest.submissions(:all).paginate(page: params[:page])
  end

  # GET /contests/new
  def new
    @contest = current_agency.contests.build
  end

  # GET /contests/1/edit/my_brands
  def edit
  end

  def winner_window
    @contest = current_agency.contests.find(params[:id])
    @post = Post.find(params[:post_id])
    @winner = @post.user
    @notification = @winner.notifications.build
    respond_to do |format|
      format.js
    end
  end

  # POST /contests
  # POST /contests.json
  def create
    @contest = current_agency.contests.build(contest_params)
    respond_to do |format|
      if @contest.save
        
        FinishContestWorker.perform_at(@contest.end_date, @contest.id) if @contest.voting?
        
        format.html { redirect_to @contest, notice: 'Contest was successfully created.' }
        format.json { render :show, status: :created, location: @contest }
      else
        format.html { render :new }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contests/1
  # PATCH/PUT /contests/1.json
  def update
    respond_to do |format|
      if @contest.update(contest_params)
        FinishContestWorker.perform_at(@contest.end_date, @contest.id)
        format.html { redirect_to @contest, notice: 'Contest was successfully updated.' }
        format.json { render :show, status: :ok, location: @contest }
      else
        format.html { render :edit }
        format.json { render json: @contest.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contests/1
  # DELETE /contests/1.json
  def destroy
    @contest.destroy
    respond_to do |format|
      format.html { redirect_to my_contests_url, notice: 'Contest was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def correct_agency
    redirect_to root_path unless @contest.brand.agency == current_agency
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_contest
    @contest = Contest.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def contest_params
    params.require(:contest).permit(:brand_id, :title, :description, :rules, :prizes, :voting, :start_date, :end_date, :location, :picture)
  end
end

app/helpers/contests_helper.rb
module ContestsHelper
end

app/views/contests/_contest.html.erb
<tr>
  <td>
    <%= image_tag contest.picture.url, class: "img img-rounded contest-image-xs" %>
  </td>
  <td class="text-center vertical-middle">
    <%= contest.brand.name %> - <%= contest.description %>
  </td>
  <td class="text-center vertical-middle">
    <%= link_to "View", contest_path(contest), class: "btn btn-default btn-xs btn-actions" %>
  </td>
  <td class="text-center vertical-middle">
    <%= link_to "Edit", edit_contest_path(contest), class: "btn btn-default btn-xs btn-actions" %>
  </td>
  <td class="text-center vertical-middle">
    <%= link_to "Delete", contest_path(contest), class: "btn btn-default btn-xs btn-actions", method: :delete, data: {confirm: "Are you sure?"} %>
  </td>
  <td class="text-center vertical-middle">
    <span class="label label-<%= contest.status == 'OPEN' ? 'success' : 'danger' %>"><%= contest.status %></span>
  </td>
</tr>

app/views/contests/_form.html.erb
<%= form_for(@contest) do |f| %>
  <% if @contest.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contest.errors.count, "error") %></h2>
      <ul>
      <% @contest.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <% if @contest.new_record? %>
    <%= image_tag "ph.jpg", class: "contest-image-sm", id: "upload-preview-contest" %>
    <%= f.file_field :picture, id: "picture-input-contest", required: true, accept: "image/*" %>
  <% else %>
    <%= image_tag @contest.picture.url, class: "contest-image-sm", id: "upload-preview-contest" %>
    <%= f.file_field :picture, id: "picture-input-contest", accept: "image/*" %>
  <% end%>
  <%= link_to "Upload Picture", "javascript:void(0);", class: "btn btn-default", id: "upload-button-contest" %>
  <br><br>
  <div class="form-group">Which brand?
    <%= f.collection_select :brand_id, current_agency.brands, :id, :name, {}, {id: "brand-selection", "data-style" => "btn-default", "data-no-turbolink" => true} %>
  </div>
  <div class="form-group">
    <%= f.text_field :title, placeholder: "Title", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :location, placeholder: "Start typing the location...", id: "autocomplete", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, placeholder: "Description", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_area :prizes, placeholder: "Prizes", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_area :rules, placeholder: "Rules", class: "form-control" %>
  </div>
  <div class="form-group">Start Date <br>
    <%= f.datetime_select :start_date, placeholder: "Start Date/Time", class: "form-control" %>
  </div>
  <div class="form-group">End Date <br>
    <%= f.datetime_select :end_date, placeholder: "End Date/Time", class: "form-control" %>
  </div>
  <div class="checkbox"><label><%= f.check_box :voting, id: "voting" %>Winner is determined by voting</label></div>
  <br>
    <%= f.submit class: "btn btn-default btn-block" %>
<% end %>
<% content_for :scripts do %>
<script src="http://maps.googleapis.com/maps/api/js?sensor=false&amp;libraries=places"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      $('#brand-selection').selectpicker();

      $('#autocomplete').keypress(function(event) { return event.keyCode != 13; });

      var placeSearch, autocomplete;
      var componentForm = {
        street_number: 'short_name',
        route: 'long_name',
        locality: 'long_name',
        administrative_area_level_1: 'short_name',
        country: 'long_name',
        postal_code: 'short_name'
      };
      autocomplete = new google.maps.places.Autocomplete(
        /** @type {HTMLInputElement} */(document.getElementById('autocomplete')),
            { types: ['geocode'] });
        // When the user selects an address from the dropdown,
        // skip to the next field.

        function geolocate() {
        if (navigator.geolocation) {
          navigator.geolocation.getCurrentPosition(function(position) {
            var geolocation = new google.maps.LatLng(
                position.coords.latitude, position.coords.longitude);
            autocomplete.setBounds(new google.maps.LatLngBounds(geolocation,
                geolocation));
          });
        }
      }
    });
  </script>
<% end %>

app/views/contests/_modal.html.erb
<%= form_for @notification, remote: true, :html => { :multipart => true } do |f| %>
<div class="modal-dialog modal-sm">
  <div class="modal-content">
    <div class="modal-header">
      <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      <h4 class="modal-title" id="myModalLabel">Notify <%= @winner.full_name %></h4>
    </div>
    <div class="modal-body">
        <div class="col-md-12">
          <%= image_tag (@notification.new_record? ? "ph.jpg" : @notification.image.url), class: "notification-image-sm", id: "upload-preview" %>
        
            <%= f.file_field :image, id: "picture-input", required: true, accept: "image/*" %>
            <%= link_to "Upload Picture", "javascript:void(0);", class: "btn btn-default", id: "upload-button" %>
        </div>
        <div class="col-md-12">
          <%= f.text_area :text, placeholder: "Message to #{@winner.full_name}", class: 'form-control notification-message-field' %>
          <%= f.hidden_field :type, value: "winner" %>
          <%= f.hidden_field :receiver_id, value: @winner.id %>
          <%= f.hidden_field :post_id, value: @post.id %>
        </div>
        
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
      <%= f.submit "Send", class: "btn btn-primary" %>
    </div>
  </div>
</div>
<% end %>

app/views/contests/edit.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="page-header">
        <h1 class="text-center">
          Edit Contest
        </h1>
      </div>
      <div class="row clearfix">
        <div class="col-md-4 col-md-offset-4 column">
          <%= render 'form' %>
          <br>
          <%= link_to 'Back', my_contests_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contests/index.html.erb
<h1>Listing contests</h1>
<table>
  <thead>
    <tr>
      <th>Brand</th>
      <th>Title</th>
      <th>Description</th>
      <th>Rules</th>
      <th>Prizes</th>
      <th>Voting</th>
      <th>Start date</th>
      <th>End date</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @contests.each do |contest| %>
      <tr>
        <td><%= contest.brand %></td>
        <td><%= contest.title %></td>
        <td><%= contest.description %></td>
        <td><%= contest.rules %></td>
        <td><%= contest.prizes %></td>
        <td><%= contest.voting %></td>
        <td><%= contest.start_date %></td>
        <td><%= contest.end_date %></td>
        <td><%= link_to 'Show', contest %></td>
        <td><%= link_to 'Edit', edit_contest_path(contest) %></td>
        <td><%= link_to 'Destroy', contest, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Contest', new_contest_path %>

app/views/contests/my_contests.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="page-header">
        <h1 class="text-center">Manage Contests</h1>
        <%= link_to "Create Contest", new_contest_path, class: "btn btn-default" %>
      </div>
      <%= will_paginate(@contests, renderer: BootstrapPagination::Rails) %>
      <table class="table text-center">
        <thead>
          <tr>
            <th class="text-center">Image</th>
            <th class="text-center">Description</th>
            <th colspan="3" class="text-center">Actions</th>
            <th class="text-center">Status</th>
          </tr>
        </thead>
        <tbody>
          <%= render @contests %>
        </tbody>
      </table>
      <%= will_paginate(@contests, renderer: BootstrapPagination::Rails) %>
    </div>
  </div>
</div>

app/views/contests/new.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="page-header">
        <h1 class="text-center">
          Create Contest
        </h1>
      </div>
      <div class="row clearfix">
        <div class="col-md-4 col-md-offset-4 column">
          <%= render 'form' %>
          <br>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contests/show.html.erb
<div class="modal fade" id="winner-modal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
</div>
<div class="container top-space">
  <div class="row clearfix">
    <div class="col-md-3 column sidebar">
      <div class="row clearfix">
        <div class="col-md-12 column">
          <%= image_tag @contest.picture.url, class: "img img-rounded contest-image-flex" %>
        </div>
      </div>
      <div class="row clearfix contest-stats">
        <div class="col-md-12 column">
          <p>Submissions Today<span class="pull-right"><%= @contest.submissions_count(:today) %></span></p>
          <p>Total Submissions<span class="pull-right"><%= @contest.submissions_count(:all) %></span></p>
          <p>Page Views<span class="pull-right"><%= @contest.impressionist_count %></span></p>
        </div>
      </div>
    </div>
    <div class="col-md-9 column">
      <div class="row clearfix">
        <div class="col-md-9 column">
           <h3 class="contest-name"><%= @contest.brand.name %> - <%= @contest.title %></h3>
           <span class="label label-<%= @contest.status == 'OPEN' ? 'success' : 'danger' %>"><%= @contest.status %></span>
        </div>
        <div class="col-md-3 column text-right">
           <%= link_to "Edit", edit_contest_path(@contest), class: "btn btn-default btn-actions-md", style: "margin-right: 1px;" if current_agency.owns? @contest %>
        </div>
      </div>
      <div class="row clearfix second-row">
        <div class="col-md-9 column">
           <p>
           	<strong>Starts date:</strong> <%= !@contest.start_date.blank? ? Time.at(@contest.start_date).strftime("%B %d, %Y - %H:%M")+" EST" : "" %><br>
            <strong>End date:</strong> <%= !@contest.end_date.blank? ? Time.at(@contest.end_date).strftime("%B %d, %Y - %H:%M")+' EST': "" %>
          </p>
        </div>
        <div class="col-md-3 column text-right">
           <%= link_to "Delete", contest_path(@contest), class: "btn btn-default btn-actions-md", method: :delete, data: {confirm: "Are you sure?"} %>
        </div>
      </div>
      <div class="row clearfix">
        <div class="col-md-12 column">
          <p><strong>Location</strong><br><%= @contest.location %></p>
          <p><strong>How to Enter</strong><br><%= @contest.description %></p>
          <p><strong>Prizes</strong><br><%= @contest.prizes %></p>
          <p><strong>Rules</strong><br><%= @contest.rules %></p>
        </div>
      </div>
      <div class="row clearfix">
        <div class="col-md-12 column">
          <h4>Current Submissions</h4>
          <%= will_paginate(@posts, renderer: BootstrapPagination::Rails) %>
          <hr>
          <%= render partial: 'posts/card', collection: @posts, as: :post %>
          <%= will_paginate(@posts, renderer: BootstrapPagination::Rails) %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/contests/winner_window.js.erb
$("#winner-modal").html("<%= escape_javascript(render 'contests/modal') %>");
var preview = $("#upload-preview");
$("#picture-input").change(function(event){
 var input = $(event.currentTarget);
 var file = input[0].files[0];
 var reader = new FileReader();
 reader.onload = function(e){
     image_base64 = e.target.result;
     preview.attr("src", image_base64);
 };
 reader.readAsDataURL(file);
});
$("#upload-button").click(function(){
$('#picture-input').trigger('click');
});
$("#winner-modal").modal('toggle');