config/routes.rb
Rails.application.routes.draw do

  devise_for :admins do
    root :to => "admins#users"
  end
  resources :posts do
    resources :comments, shallow: true
  end

  resources :contests do
    member do
      post 'set_winner'
      get 'winner_window'
    end
    collection do
      get 'my', path: "my_contests"
    end
  end

  resources :brands do
    collection do
      get 'my', path: "my_brands"
      post :visit_brand_social
    end
  end
  post '/admins/agencies/:agency_id/disable' => 'admins#disable_agency', as: 'disable_agency'
  post '/admins/agencies/:agency_id/enable' => 'admins#enable_agency', as: 'enable_agency'
  post '/admins/users/:user_id/disable' => 'admins#disable_user', as: 'disable_user'
  post '/admins/users/:user_id/enable' => 'admins#enable_user', as: 'enable_user'
  delete '/admins/agencies/:agency_id/delete' => 'admins#delete_agency', as: 'delete_agency'
  delete '/admins/users/:user_id/delete' => 'admins#delete_user', as: 'delete_user'
  get '/admins/agencies' => 'admins#agencies', as: 'admin_agencies'
  get '/admins/users' => 'admins#users', as: 'admin_users'
  get '/admins' => 'admins#users', as: 'admin_root_path'

  resources :notifications

  devise_for :agencies, controllers: {registrations: "agency_registrations"}
  devise_for :users, :controllers => {passwords: "password" }
  post '/users/password' => 'password#create', :as => :user_forgot_password, :via => :post
  get 'agencies/change_password' => 'agencies#change_password'
  post 'agencies/update_password' => 'agencies#update_password'

  namespace :api, :defaults => {:format => :json} do

    resources :posts do
      member do
        get 'comments'
        post 'like'
        post 'unlike'
      end
      collection do
        get 'by_brand'
        get 'by_user'
        get 'by_contest'
        get 'my', path: "my_posts"
        get 'stream'
        get :show_without_authenticate
      end
    end
    resources :contests do
      collection do
        get 'by_brand'
        get 'by_following'
      end
      member do
        post 'claim_prize'
      end
    end

    resources :brands do
      member do
        post 'click'
        post 'follow'
        post 'unfollow'
        get 'check_follow'
      end
    end

    resources :comments

    get 'users/login' => 'users#login'
    resources :users do
      collection do
        get 'search'
        get :get_users
        post :update_facebook
        post :update_twitter
        post :update_instagram
      end
      member do
        post 'follow'
        post 'unfollow'
        get 'check_follow'
        post 'save_token'
        get 'followers'
        get 'following'
        get 'contests'
        get 'get_all_expose_of_user'
      end
    end
    post 'profile/update' => 'users#update_my_profile', as: 'update_profile'
    get 'profile' => 'users#profile'

    resources :notifications, only: :index do
      collection do
        post :read_notification
        get :count_unread_notifications
      end
    end

    resources :agencies

    get 'rankings/global' => 'rankings#global'
    get 'rankings/followers' => 'rankings#followers'
    get 'rankings/following' => 'rankings#following'

  end

  root 'brands#my'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

end

app/models/post.rb
class Post < ActiveRecord::Base
  self.per_page = 18
  belongs_to :user, foreign_key: "uploader_id"
  belongs_to :contest
  has_many :comments, dependent: :destroy
  before_save :decode_image_data
  acts_as_votable
  attr_accessor :image_data
  has_attached_file :image,
                    storage: :s3,
                    s3_credentials: File.join(Rails.root, 'config', 's3.yml'),
                    :styles => { preview: "600x600^", square: "600x600^", thumb: "100x100^" },
                    :default_url => lambda { |image| ActionController::Base.helpers.asset_path('ph.jpg') }
  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/, presence: true
  
  def image_url
    self.image.url
  end

  def image_url_thumb
    self.image.url(:thumb)
  end

  def image_url_preview
    self.image.url(:preview)
  end

  def image_url_square
    self.image.url(:square)
  end

  def current_user_likes
    User.current.liked?(self) if User.current
  end

  def brand
    if self.contest
      self.contest.brand.id
    end
  end

  def selected
    self.update_attributes(is_selected: true)
  end

  private

  def decode_image_data
    # If image_data is present, it means that we were sent an image over
    # JSON and it needs to be decoded.  After decoding, the image is processed
    # normally via Paperclip.
    if self.image_data.present?
        data = StringIO.new(Base64.decode64(self.image_data))
        data.class.class_eval {attr_accessor :original_filename, :content_type}
        data.original_filename = "photo"
        data.content_type = "image/jpg"
        self.image = data
    end
  end

end

app/controllers/api/posts_controller.rb
class API::PostsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :authenticate_user_from_token!, only: [:create, :my, :like, :unlike, :update]
  respond_to :json
  include ApplicationHelper
  def create
    @post = current_user.posts.build(post_params)
    logger.info "------------------- log post param when create -------------------------------"
    logger.info post_params
    if @post.save
      respond_with @post, only: [:id, :contest_id, :uploader_id, :text, :cached_votes_up, :created_at], methods: [:image_url, :image_url_square, :image_url_preview, :image_url_thumb, :brand, :current_user_likes], location: "/"
    else
      respond_with @post.errors, status: :unprocessable_entity, location: "/"
    end
  end

  def update
    @post = Post.find_by_id(params[:id])
    logger.info "---------------------------------- log post param when update #########################"
    if @post.update_attributes(post_params)
      respond_with @post do |format|
        format.json {render json: @post, only: [:id, :contest_id, :uploader_id, :text, :cached_votes_up, :created_at], methods: [:image_url, :image_url_square, :image_url_preview, :image_url_thumb, :brand, :current_user_likes], location: "/"}
      end
    else
      logger.info "################## post not updated #####"
      logger.info @post.errors
      respond_with @post.errors, status: :unprocessable_entity, location: "/"
    end
  end

  def show
    @post = Post.find(params[:id])
    logger.info "################## post #{@post.as_json}"
    if params[:user_token]
      respond_with @post, only: [:id, :contest_id, :uploader_id, :text, :cached_votes_up, :created_at], methods: [:image_url, :image_url_square, :image_url_preview, :image_url_thumb, :brand, :current_user_likes], location: "/"
    else
      respond_with @post, only: [:id, :contest_id, :uploader_id, :text, :cached_votes_up, :created_at], methods: [:image_url, :image_url_square, :image_url_preview, :image_url_thumb, :brand], location: "/"
    end
  end

  def show_without_authenticate
    @post = Post.find(params[:id])
    logger.info "################## post #{@post.as_json} without authenticate"
    respond_with render_post_with_include_comments(@post), location: "/"
  end

  def index
    @posts = Post.all.paginate(page: params[:page]).order(created_at: :desc)
    respond_with @posts, only: [:contest_id, :uploader_id, :text, :cached_votes_up, :id, :created_at], methods: [:image_url, :image_url_square, :image_url_preview, :image_url_thumb, :brand, :current_user_likes], location: "/"
  end

  def by_user
    @posts = Post.where(uploader_id: params[:user_id]).paginate(page: params[:page]).order(created_at: :desc)
    respond_with @posts, only: [:contest_id, :uploader_id, :text, :cached_votes_up, :id, :created_at], methods: [:image_url, :image_url_square, :image_url_preview, :image_url_thumb, :brand, :current_user_likes], location: "/"
  end

  def by_contest
    @posts = Post.where(contest_id: params[:contest_id]).paginate(page: params[:page]).order(created_at: :desc)
    respond_with @posts, only: [:contest_id, :uploader_id, :text, :cached_votes_up, :id, :created_at], methods: [:image_url, :image_url_square, :image_url_preview, :image_url_thumb, :brand, :current_user_likes], location: "/"
  end

  def by_brand
    @posts = Post.where("contest_id in (select id from contests where brand_id = ?)", params[:brand_id]).paginate(page: params[:page]).order(created_at: :desc)
    respond_with @posts, only: [:contest_id, :uploader_id, :text, :cached_votes_up, :id, :created_at], methods: [:image_url, :image_url_square, :image_url_preview, :image_url_thumb, :brand, :current_user_likes], location: "/"
  end

  def stream
    user_email = params[:user_email].presence
    user       = user_email && User.find_by_email(user_email)
    if user && Devise.secure_compare(user.authentication_token, params[:user_token])
      sign_in user, store: false
      set_current_user
      user = current_user
      @posts = Post.where("uploader_id in (?)", user.following_users.pluck(:id)).paginate(page: params[:page]).order(created_at: :desc)
      respond_with @posts, only: [:contest_id, :uploader_id, :text, :cached_votes_up, :id, :created_at], methods: [:image_url, :image_url_square, :image_url_preview, :image_url_thumb, :brand, :current_user_likes], location: "/"
    else
      @posts = Post.all.paginate(page: params[:page]).order(created_at: :desc)
      respond_with @posts, only: [:contest_id, :uploader_id, :text, :cached_votes_up, :id, :created_at], methods: [:image_url, :image_url_square, :image_url_preview, :image_url_thumb, :brand], location: "/"
    end
  end

  def my
    @posts = current_user.posts.paginate(page: params[:page]).order(created_at: :desc)
    respond_with @posts, only: [:contest_id, :uploader_id, :text, :cached_votes_up, :id, :created_at], methods: [:image_url, :image_url_square, :image_url_preview, :image_url_thumb, :brand, :current_user_likes], location: "/"
  end

  def comments
    list = Comment.includes(:user).where(post_id: params[:id]).paginate(page: params[:page]).order(created_at: :asc)
    @comments = comment_response_with_include_user_avatar_url(list)
    respond_with @comments, location: "/"
  end

  def like
    post = Post.find(params[:id])
    user = current_user
    like = user.likes post
    post_owner = post.user
    post_owner.update_attributes(cached_score: post_owner.cached_score + 1)
    Notification.create(sender_id: user.id, receiver_id: post_owner.id,
      text: "#{user.full_name} liked your photo on eXposure!", sender_type: "user", type: "like", post_id: post.id,
      sender_picture: user.profile_picture_url_thumb, sender_name: user.full_name, contest_id: post.contest_id)
    json = {status: like, like: user.voted_for?(post)}
    respond_with json, location: "/"
  end

  def unlike
    post = Post.find(params[:id])
    user = current_user
    like = user.unlike post
    post_owner = post.user
    post_owner.update_attributes(cached_score: post_owner.cached_score - 1)
    json = {status: like, like: current_user.voted_for?(post)}
    respond_with json, location: "/"
  end

  private

  def post_params
    params[:post].permit(:contest_id, :image_data, :text)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  #before_action :authenticate_user!, only: [:create, :update, :destroy, :edit, :new]
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update]

  # GET /posts
  # GET /posts.json
  # def index
  #   @posts = Post.all
  # end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments=@post.comments.paginate(page: params[:page])
  end

  # GET /posts/new
  # def new
  #   @post = Post.new
  # end

  # GET /posts/1/edit
  # def edit
  # end

  # POST /posts
  # POST /posts.json
  # def create
  #   @post = Post.new(post_params)

  #   respond_to do |format|
  #     if @post.save
  #       format.html { redirect_to @post, notice: 'Post was successfully created.' }
  #       format.json { render :show, status: :created, location: @post }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @post.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  # def update
  #   respond_to do |format|
  #     if @post.update(post_params)
  #       format.html { redirect_to @post, notice: 'Post was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @post }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @post.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to contest_url(:id => params[:contest_id]) , notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_post
    @post = Post.find(params[:id])
  end

  def corrent_user
    redirect_to root_path unless (@post.user == current_user || @post.contest.agency == current_agency)
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def post_params
    params.require(:post).permit(:uploader_id, :contest_id, :text)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_card.html.erb
<div class="post-card">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="first-row">
        <%= image_tag post.user.profile_picture.url(:square), class: "avatar" %><%= post.user.full_name %>
        <span class="pull-right">
          <%= link_to post_path(id: post.id, contest_id: post.contest), method: :delete, data: {confirm: "Are you sure?"} do %>
            <i class="fa fa-times"> </i>
          <% end %>
        </span>
      </div>
      <div class="row clearfix image-row">
        <div class="col-md-12 column">
          <%= link_to (image_tag post.image.url(:square)), post_path(post) %>
        </div>
      </div>
      <div class="row clearfix actions-row">
        <div class="col-md-8 column">
          <p>
            <i class="fa fa-heart" style="font-size: 12px;"> </i><%= post.get_likes.size %> <i class="fa fa-comments"> </i><%= post.comments.count %>
          </p>
        </div>
        <div class="col-md-4 column text-right">
          <p>
            <%= time_ago_in_words(post.created_at).gsub(/minutes|minute/, "m").gsub(/hour|hours/, "h") %>
          </p>
        </div>
      </div>
      <div class="row clearfix winner-row">
        <div class="col-md-12 column">
          <p id="winner-field-<%= post.user.id %>">
            <% if post.is_selected %>
              <i class="fa fa-certificate"> </i>Winner!
            <% else %>
            <!-- set_winner_contest_path(id: @contest.id, post_id: "1") -->
              <%= link_to "Select as Winner", winner_window_contest_path(post_id: post.id), remote: true %>
            <% end %>
          </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uploader_id %><br>
    <%= f.number_field :uploader_id %>
  </div>
  <div class="field">
    <%= f.label :contest_id %><br>
    <%= f.number_field :contest_id %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>
<table>
  <thead>
    <tr>
      <th>Uploader</th>
      <th>Contest</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.uploader_id %></td>
        <td><%= post.contest_id %></td>
        <td><%= post.text %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="container" style="padding-top: 20px;">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="row clearfix">
        <div class="column image-show-size vertical-middle">
          <%= image_tag @post.user.profile_picture.url(:square), class: "avatar" %><%= @post.user.full_name %><br><br>
        </div>
        <div class="column image-show-size">
          <%= image_tag @post.image.url, style: "width: 100%;" %>
        </div>
        <div class="row clearfix actions-row image-show-size">
          <div class="col-md-6 column">
            <p>
              <i class="fa fa-heart" style="font-size: 12px;"> </i><%= @post.get_likes.size %> <i class="fa fa-comments"> </i><%= @post.comments.count %>
            </p>
          </div>
          <div class="col-md-6 column text-right">
            <p>
              <%= time_ago_in_words(@post.created_at) %> ago
            </p>
          </div>
        </div>
      </div>
      <div class="row clearfix">
        <div class="comments-list">
          <%= render @comments %>
          <%= will_paginate @comments %>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<br>
<br>