config/routes.rb
Rails.application.routes.draw do

  devise_for :admins do
    root :to => "admins#users"
  end
  resources :posts do
    resources :comments, shallow: true
  end

  resources :contests do
    member do
      post 'set_winner'
      get 'winner_window'
    end
    collection do
      get 'my', path: "my_contests"
    end
  end

  resources :brands do
    collection do
      get 'my', path: "my_brands"
      post :visit_brand_social
    end
  end
  post '/admins/agencies/:agency_id/disable' => 'admins#disable_agency', as: 'disable_agency'
  post '/admins/agencies/:agency_id/enable' => 'admins#enable_agency', as: 'enable_agency'
  post '/admins/users/:user_id/disable' => 'admins#disable_user', as: 'disable_user'
  post '/admins/users/:user_id/enable' => 'admins#enable_user', as: 'enable_user'
  delete '/admins/agencies/:agency_id/delete' => 'admins#delete_agency', as: 'delete_agency'
  delete '/admins/users/:user_id/delete' => 'admins#delete_user', as: 'delete_user'
  get '/admins/agencies' => 'admins#agencies', as: 'admin_agencies'
  get '/admins/users' => 'admins#users', as: 'admin_users'
  get '/admins' => 'admins#users', as: 'admin_root_path'

  resources :notifications

  devise_for :agencies, controllers: {registrations: "agency_registrations"}
  devise_for :users, :controllers => {passwords: "password" }
  post '/users/password' => 'password#create', :as => :user_forgot_password, :via => :post
  get 'agencies/change_password' => 'agencies#change_password'
  post 'agencies/update_password' => 'agencies#update_password'

  namespace :api, :defaults => {:format => :json} do

    resources :posts do
      member do
        get 'comments'
        post 'like'
        post 'unlike'
      end
      collection do
        get 'by_brand'
        get 'by_user'
        get 'by_contest'
        get 'my', path: "my_posts"
        get 'stream'
        get :show_without_authenticate
      end
    end
    resources :contests do
      collection do
        get 'by_brand'
        get 'by_following'
      end
      member do
        post 'claim_prize'
      end
    end

    resources :brands do
      member do
        post 'click'
        post 'follow'
        post 'unfollow'
        get 'check_follow'
      end
    end

    resources :comments

    get 'users/login' => 'users#login'
    resources :users do
      collection do
        get 'search'
        get :get_users
        post :update_facebook
        post :update_twitter
        post :update_instagram
      end
      member do
        post 'follow'
        post 'unfollow'
        get 'check_follow'
        post 'save_token'
        get 'followers'
        get 'following'
        get 'contests'
        get 'get_all_expose_of_user'
      end
    end
    post 'profile/update' => 'users#update_my_profile', as: 'update_profile'
    get 'profile' => 'users#profile'

    resources :notifications, only: :index do
      collection do
        post :read_notification
        get :count_unread_notifications
      end
    end

    resources :agencies

    get 'rankings/global' => 'rankings#global'
    get 'rankings/followers' => 'rankings#followers'
    get 'rankings/following' => 'rankings#following'

  end

  root 'brands#my'

  get "/404", :to => "errors#not_found"
  get "/422", :to => "errors#unacceptable"
  get "/500", :to => "errors#internal_error"

end

app/models/brand.rb
class Brand < ActiveRecord::Base
  self.per_page = 18
  belongs_to :agency
  has_many :contests, dependent: :destroy
  acts_as_followable
  is_impressionable :counter_cache => true, :column_name => :cached_views, :unique => :request_hash
  has_many :photos, :dependent => :destroy
  accepts_nested_attributes_for :photos, :allow_destroy => true
  validates_presence_of :name
  has_attached_file :picture,
      storage: :s3,
      s3_credentials: File.join(Rails.root, 'config', 's3.yml'),
      :styles => { preview: "600x600^", square: "600x600^", thumb: "100x100^" },
      :default_url => lambda { |image| ActionController::Base.helpers.asset_path('ph.jpg') }
  def submissions
    Post.where("contest_id in (select id from contests where brand_id=?)", self.id).order(created_at: :desc)
  end

  def submissions_mobile
    submissions.map do |s|
      {id: s.id,
     contest_id: s.contest_id,
     uploader_id: s.uploader_id,
     text: s.text,
     cached_votes_up: s.cached_votes_up,
     image_url: s.image_url,
     image_url_square: s.image_url_square,
     image_url_preview: s.image_url_preview,
     image_url_thumb: s.image_url_thumb,
     brand: s.brand,
     current_user_likes: s.current_user_likes
    }
    end
  end
  def submissions_count
    self.submissions.count
  end
  def picture_url
    self.photos[0].picture.url
  end
  def picture_url_square
    self.photos[0].picture_url_square
  end
  def picture_url_preview
    self.photos[0].picture_url_preview
  end
  def picture_url_thumb
    self.photos[0].picture_url_thumb
  end
  def background_url
    self.photos[1].picture.url
  end
  def background_url_square
    self.photos[1].picture_url_square
  end
  def background_url_preview
    self.photos[1].picture_url_preview
  end
  def background_url_thumb
    self.photos[1].picture_url_thumb
  end

  def winners
    w = []
    self.contests.each do |c|
      x = c.winners.map do |u|
        {
          id: u.id,
          email: u.email,
          first_name: u.first_name,
          last_name: u.last_name,
          username: u.username,
          profile_picture_url: u.profile_picture_url,
          profile_picture_url_thumb: u.profile_picture_url_thumb,
          profile_picture_url_preview: u.profile_picture_url_preview,
          profile_picture_url_square: u.profile_picture_url_square,
          background_picture_url: u.background_picture_url,
          background_picture_url_preview: u.background_picture_url_preview
        }
      end
      w += x unless x.nil?
    end
    w
  end

  def followers_list
    self.followers.map do |u|
      {
          id: u.id,
          email: u.email,
          first_name: u.first_name,
          last_name: u.last_name,
          username: u.username,
          profile_picture_url: u.profile_picture_url,
          profile_picture_url_thumb: u.profile_picture_url_thumb,
          profile_picture_url_preview: u.profile_picture_url_preview,
          profile_picture_url_square: u.profile_picture_url_square,
          background_picture_url: u.background_picture_url,
          background_picture_url_preview: u.background_picture_url_preview
        }
    end
  end

  def winners_count
    a = 0
    contests.each do |c|
      a += c.winners.count
    end
    a
  end

  def link_clicks(target)
    self.impressionist_count(message: target, :filter=>:all)
  end

end

app/controllers/api/brands_controller.rb
class API::BrandsController < ApplicationController
  skip_before_filter :verify_authenticity_token
  before_action :authenticate_user_from_token!, only: [:follow, :unfollow, :check_follow]
  respond_to :json

  def index
    @brands = Brand.all.paginate(page: params[:page]).order(created_at: :desc)
    respond_with @brands, methods: [:picture_url, :picture_url_preview, :picture_url_square, :picture_url_thumb], location: "/"
  end

  def show
    @brand = Brand.find(params[:id])
    impressionist(@brand, "brandview")
    respond_with @brand, methods: [:picture_url, :picture_url_preview, :picture_url_square, :picture_url_thumb,
                                   :background_url, :background_url_preview, :background_url_square, :background_url_thumb,:submissions_mobile, :submissions_count, :winners_count, :winners, :followers_count, :followers_list], location: "/"
  end

  def follow
    brand = Brand.find(params[:id])
    current_user.follow(brand)
    json = {status: true, following: true}
    respond_with json, location: "/"
  end

  def unfollow
    brand = Brand.find(params[:id])
    current_user.stop_following(brand)
    json = {status: true, following: false}
    respond_with json, location: "/"
  end

  def check_follow
    brand = Brand.find(params[:id])
    json = {status: true, following: current_user.following?(brand)}
    respond_with json, location: "/"
  end

  def click
    if params[:target] && ["website", "facebook", "twitter", "instagram"].include?(params[:target])
      @brand = Brand.find(params[:id])
      impressionist(@brand, params[:target])
      @json = {status: true}
      respond_with @json, location: "/"
    else
      @json = {status: false, message: "Wrong or no target specified"}
      respond_with @json, status: :unprocessable_entity, location: "/"
    end
  end

end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController
  include BrandsHelper
  before_filter :authenticate_admin!, only: [:index]
  before_action :authenticate_agency!, only: [:create, :update, :destroy, :edit, :new, :my]
  before_action :set_brand, only: [:show, :edit, :update, :destroy]
  before_action :correct_agency, only: [:edit, :update, :destroy]
  # GET /brands
  # GET /brands.json
  def index
    @brands = Brand.all
  end

  def my
    #Rails.logger.error(User.find(43).device_token)
    @brands = current_agency.brands.paginate(page: params[:page])
    render 'my_brands'
  end

  # GET /brands/1
  # GET /brands/1.json
  def show
    @contests = @brand.contests.paginate(page: params[:page])
    impressionist(@brand, 'brandview', :unique => [:impressionable_type, :impressionable_id, :session_hash])
  end

  # GET /brands/new
  def new
    @brand = current_agency.brands.build
    2.times {@brand.photos.build}
  end

  # GET /brands/1/edit
  def edit
  end

  # POST /brands
  # POST /brands.json
  def create
    @brand = current_agency.brands.build(brand_params)

    respond_to do |format|
      if @brand.save
        format.html { redirect_to @brand, notice: 'Brand was successfully created.' }
        format.json { render :show, status: :created, location: @brand }
      else
        format.html { render :new }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /brands/1
  # PATCH/PUT /brands/1.json
  def update
    respond_to do |format|
      if @brand.update(brand_params)
        format.html { redirect_to @brand, notice: 'Brand was successfully updated.' }
        format.json { render :show, status: :ok, location: @brand }
      else
        format.html { render :edit }
        format.json { render json: @brand.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /brands/1
  # DELETE /brands/1.json
  def destroy
    @brand.destroy
    respond_to do |format|
      format.html { redirect_to my_brands_url, notice: 'Brand was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def visit_brand_social
    if params[:target] && ["website", "facebook", "twitter", "instagram"].include?(params[:target])
      @brand = Brand.find(params[:id])
      impressionist(@brand, params[:target])
      redirect_to redirect_types(params[:target],@brand)
    else
      @json = {status: false, message: "Wrong or no target specified"}
      respond_with @json, status: :unprocessable_entity, location: "/"
    end
  end

  private
  def correct_agency
    redirect_to root_path unless @brand.agency == current_agency
  end
  # Use callbacks to share common setup or constraints between actions.
  def set_brand
    @brand = Brand.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def brand_params
    params.require(:brand).permit(:name, :facebook, :twitter, :instagram, :slogan, :website, :description, :picture,
                                  photos_attributes: [:picture, :id])
  end
end

app/helpers/brands_helper.rb
module BrandsHelper
  def redirect_types(type,brand)
    case type
    when 'twitter'
      "http://twitter.com/" + brand.twitter
    when 'website'
      brand.website
    when 'facebook'
      brand.facebook
    when 'instagram'
      "http://instagram.com/" + brand.instagram
    end
  end
end

app/views/brands/_brand.html.erb
<tr>
  <td>
    <% brand.photos.each do |photo|%>
      <%= image_tag photo.picture_url, class: "img img-rounded brand-image-xs upload-preview" %>
    <% end %>
  </td>
  <td class="text-center vertical-middle">
    <%= brand.name %> - <%= brand.description %>
  </td>
  <td class="text-center vertical-middle">
    <%= link_to "View", brand_path(brand), class: "btn btn-default btn-xs btn-actions" %>
  </td>
  <td class="text-center vertical-middle">
    <%= link_to "Edit", edit_brand_path(brand), class: "btn btn-default btn-xs btn-actions" %>
  </td>
  <td class="text-center vertical-middle">
    <%= link_to "Delete", brand_path(brand), class: "btn btn-default btn-xs btn-actions", method: :delete, data: {confirm: "Are you sure?"} %>
  </td>
</tr>

app/views/brands/_form.html.erb
<div class="brand-new">
<%= form_for @brand, :html => { :multipart => true } do |f| %>
  <% if @brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brand.errors.count, "error") %></h2>
      <ul>
      <% @brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
    <% index = 0%>
    <%= f.fields_for :photos, @brand.photos do |f_photo| %>
      <% if f_photo.object.new_record? %>
        <output id="list-image-<%= index %>" class="brand-image-with-span-remove">
          <span id="span-upload-preview-<%= index %>">
            <span></span>
            <%= image_tag "ph.jpg", class: "brand-image-sm upload-preview", id: "upload-preview-#{index}" %>
            <%= f_photo.file_field :picture, id: "picture-input-#{index}", required: true, accept: "image/*", class: 'picture-brand'%>
          </span>
          <br></br>
        <%= link_to "Upload Picture", "javascript:void(0);", class: "btn btn-default btn-xs", id: "upload-button-#{index}" %>
        </output>
      <% else %>
          <output id="list-image-<%= index %>" class="brand-image-with-span-remove">
          <%= f_photo.hidden_field :id%>
          <%= f_photo.file_field :picture, id: "picture-input-#{index}", accept: "image/*", class: 'picture-brand'%>
          <span id="span-upload-preview-<%= index %>">
            <span class="remove_img_preview"></span>
            <%= image_tag f_photo.object.picture_url, class: "brand-image-sm upload-preview", id: "upload-preview-#{index}" %>
          </span>
          <br></br>
          <%= link_to "Upload Picture", "javascript:void(0);", class: "btn btn-default btn-xs", id: "upload-button-#{index}" %>
          </output>
      <% end %>
      <% index += 1 %>
    <% end %>
  </div>
  <div class="form-group">
    <%= f.text_field :name, placeholder: "Name", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_field :slogan, placeholder: "Slogan", class: "form-control" %>
  </div>
  <div class="form-group">
    <% if f.object.website.blank? %>
      <%= f.url_field :website, placeholder: "Website", class: "form-control", value: "http://" %>
    <% else %>
      <%= f.url_field :website, placeholder: "Website", class: "form-control" %>
    <% end %>
  </div>
  <div class="form-group"><%= f.url_field :facebook, placeholder: "Facebook URL", class: "form-control" %></div>
  <div class="form-group input-group">
    <span class="input-group-addon">@</span>
    <%= f.text_field :twitter, placeholder: "Twitter username", class: "form-control" %>
  </div>
  <div class="form-group input-group">
    <span class="input-group-addon">@</span>
    <%= f.text_field :instagram, placeholder: "Instagram username", class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.text_area :description, placeholder: "Description", class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-default btn-block" %>
  </div>
<% end %>
</div>

app/views/brands/edit.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="page-header">
        <h1 class="text-center">
          Edit Brand
        </h1>
      </div>
      <div class="row clearfix">
        <div class="col-md-4 col-md-offset-4 column">
          <%= render 'form' %>
          <br>
          <%= link_to 'Back', my_brands_path %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/brands/index.html.erb
<h1>Listing brands</h1>

<table>
  <thead>
    <tr>
      <th>Agency</th>
      <th>Name</th>
      <th>Facebook</th>
      <th>Twitter</th>
      <th>Instagram</th>
      <th>Slogan</th>
      <th>Website</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.agency %></td>
        <td><%= brand.name %></td>
        <td><%= brand.facebook %></td>
        <td><%= brand.twitter %></td>
        <td><%= brand.instagram %></td>
        <td><%= brand.slogan %></td>
        <td><%= brand.website %></td>
        <td><%= brand.description %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>

app/views/brands/my_brands.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="page-header">
        <h1 class="text-center">
          Manage Brands
        </h1>
				<%= link_to "Create Brand", new_brand_path, class: "btn btn-default" %>
			</div>
			<%= will_paginate(@brands, renderer: BootstrapPagination::Rails) %>
			<table class="table text-center">
				<thead>
					<tr>
						<th class="text-center">
							Image
						</th>
						<th class="text-center">
							Description
						</th>
						<th colspan="3" class="text-center">
							Actions
						</th>
					</tr>
				</thead>
				<tbody>
					<%= render @brands %>
 				</tbody>
			</table>
			<%= will_paginate(@brands, renderer: BootstrapPagination::Rails) %>
		</div>
	</div>
</div>

app/views/brands/new.html.erb
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="page-header">
        <h1 class="text-center">
          Create Brand
        </h1>  
      </div>
      <div class="row clearfix">
        <div class="col-md-4 col-md-offset-4 column">
			<%= render 'form' %>
			<br>
			<%= link_to 'Back', my_brands_path %>
		</div>
      </div>
    </div>
  </div>
</div>

app/views/brands/show.html.erb
<div class="container top-space">
  <div class="row clearfix">
    <div class="col-md-3 column sidebar">
      <div class="row clearfix">
        <div class="col-md-12 column">
          <%= image_tag @brand.photos[0].picture.url, class: "img img-rounded brand-image-flex" %>
        </div>
      </div>
      <div class="row clearfix brand-stats">
        <div class="col-md-12 column">
          <p>Followers<span class="pull-right"><%= @brand.followers_count %></span></p>
          <p>Total Submissions<span class="pull-right"><%= @brand.submissions_count %></span></p>
          <p>
            Page Views
            <span class="pull-right"><%= @brand.impressionist_count(:message => 'brandview') %></span>
          </p>
          <hr>
          <p>
            <strong>Social Virality</strong>
          </p>
          <p>
            Website
            <span id="website" class="pull-right"><%= @brand.link_clicks("website") %></span>
          </p>
          <p>
            Facebook
            <span id="facebook" class="pull-right"><%= @brand.link_clicks("facebook") %></span>
          </p>
          <p>
            Twitter
            <span id="twitter" class="pull-right"><%= @brand.link_clicks("twitter") %></span>
          </p>
          <p>
            Instagram
            <span id="instagram" class="pull-right"><%= @brand.link_clicks("instagram") %></span>
          </p>
        </div>
      </div>
    </div>
    <div class="col-md-9 column">
      <div class="row clearfix">
        <div class="col-md-8 column">
           <h3 class="brand-name"><%= @brand.name %></h3>
        </div>
        <div class="col-md-4 column text-right">
          <%= link_to visit_brand_social_brands_path(:target => 'facebook', :id => @brand.id), method: :post, class: "btn btn-default btn-small tracker", :'data-tracker' => "facebook" do %>
            <i class="fa fa-facebook"> </i>
          <% end %>
          <%= link_to visit_brand_social_brands_path(:target => 'twitter', :id => @brand.id), method: :post, class: "btn btn-default btn-small tracker", :'data-tracker' => "twitter" do %>
            <i class="fa fa-twitter"> </i>
          <% end %>
          <%= link_to visit_brand_social_brands_path(:target => 'instagram', :id => @brand.id),  method: :post, class: "btn btn-default btn-small tracker", :'data-tracker' => "instagram" do %>
            <i class="fa fa-instagram"> </i>
          <% end %>
           <%= link_to "Edit", edit_brand_path(@brand), class: "btn btn-default btn-actions-md", style: "margin-right: 1px;" if current_agency.owns? @brand %>
        </div>
      </div>
      <div class="row clearfix second-row">
        <div class="col-md-9 column">
           <%= link_to @brand.website, visit_brand_social_brands_path(:target => 'website', :id => @brand.id), class: "tracker", method: :post, :'data-tracker' => "website" %>
        </div>
        <div class="col-md-3 column text-right">
           <%= link_to "Delete", brand_path(@brand), class: "btn btn-default btn-actions-md", method: :delete, data: {confirm: "Are you sure?"} %>
        </div>
      </div>
      <div class="row clearfix">
        <div class="col-md-12 column">
          <p>
            <strong><%= @brand.slogan %></strong>
          </p>
          <p>
            <%= @brand.description %>
          </p>
          <br>
          <br>
          <%= link_to "Create Contest", new_contest_path, class: "btn btn-default" %>
          <br><br>

          <table class="table text-center">
            <tbody>
              <%= render @contests, template: 'contests/contest' %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>